version: "3"

services:
  server:
    build:
      context: ./stof-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - backbone
  ui:
    build:
      context: ./stof-frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: prod
    ports:
      - 80:80
    networks:
      - backbone
networks:
  backbone:
