version: "3"

services:
  server:
    build:
      context: ./stof-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    network_mode: "host"
  web:
    build:
      context: ./stof-frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    network_mode: "host"
