version: "3"

services:
  server:
    build:
      context: ./stof-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - backbone
  web:
    build:
      context: ./stof-frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    depends_on:
      - server
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
